// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env", override: true });
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer Supabase direct connection for Prisma CLI/migrations.
    // Runtime app code still uses DATABASE_URL through Prisma Client.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
